In [1]:
print("Jai Maa Kali")

Jai Maa Kali


In [2]:
#the Process of choosing optimal parameter is called Hyper Parameter tunning

In [1]:
print("Jai Maa Kali")

Jai Maa Kali


In [2]:
from sklearn.datasets import load_iris

In [5]:
from sklearn import svm

In [3]:
x=load_iris()

In [4]:
x

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [1]:
print("Jai Maa Kali")

Jai Maa Kali


In [2]:
import pandas as pd

In [5]:
from sklearn import svm

In [21]:
from sklearn.datasets import load_iris

In [192]:
df=load_iris()

In [193]:
df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [194]:
x=pd.DataFrame(df.data,columns=df.feature_names)

In [195]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [196]:
x['flower']=df.target

In [197]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [198]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [199]:
x['flower']=x.flower.apply(lambda x : fun(x) )

In [200]:
def fun(x):
    if x==0:
        return "setosa"
    elif x==1:
        return "versicolor"
    else:
        return "virginica"

In [201]:
x['flower']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: flower, Length: 150, dtype: object

In [202]:
x[x.flower=='versicolor']

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   
55                5.7               2.8                4.5               1.3   
56                6.3               3.3                4.7               1.6   
57                4.9               2.4                3.3               1.0   
58                6.6               2.9                4.6               1.3   
59                5.2               2.7                3.9               1.4   
60                5.0               2.0                3.5               1.0   
61                5.9               3.0                4.2               1.5   
62                6.0               2.2                4.0               1.0   
63                6.1               2.9                4.7               1.4   
64                5.6               2.9                3.6               1.3   
65                6.7               3.1                4.4               1.4   
66                5.6               3.0                4.5               1.5   
67                5.8               2.7                4.1               1.0   
68                6.2               2.2                4.5               1.5   
69                5.6               2.5                3.9               1.1   
70                5.9               3.2                4.8               1.8   
71                6.1               2.8                4.0               1.3   
72                6.3               2.5                4.9               1.5   
73                6.1               2.8                4.7               1.2   
74                6.4               2.9                4.3               1.3   
75                6.6               3.0                4.4               1.4   
76                6.8               2.8                4.8               1.4   
77                6.7               3.0                5.0               1.7   
78                6.0               2.9                4.5               1.5   
79                5.7               2.6                3.5               1.0   
80                5.5               2.4                3.8               1.1   
81                5.5               2.4                3.7               1.0   
82                5.8               2.7                3.9               1.2   
83                6.0               2.7                5.1               1.6   
84                5.4               3.0                4.5               1.5   
85                6.0               3.4                4.5               1.6   
86                6.7               3.1                4.7               1.5   
87                6.3               2.3                4.4               1.3   
88                5.6               3.0                4.1               1.3   
89                5.5               2.5                4.0               1.3   
90                5.5               2.6                4.4               1.2   
91                6.1               3.0                4.6               1.4   
92                5.8               2.6                4.0               1.2   
93                5.0               2.3                3.3               1.0   
94                5.6               2.7                4.2               1.3   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99  

In [203]:
from sklearn.model_selection import train_test_split
X=x.drop(['flower'],axis=1)

In [204]:
y=df.target

In [205]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [66]:
model=svm.SVC(kernel='rbf',gamma='auto',C=30)

In [67]:
model.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [68]:
model.score(x_test,y_test)

0.9333333333333333

In [70]:
from sklearn.model_selection import cross_val_score

In [77]:
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),df.data,df.target,cv=3)

array([0.98, 0.94, 0.96])

In [78]:
cross_val_score(svm.SVC(kernel='linear',C=1,gamma='auto'),df.data,df.target,cv=3)

array([1.  , 1.  , 0.98])

In [81]:
cross_val_score(svm.SVC(kernel='rbf',C=60,gamma='auto'),df.data,df.target,cv=3)

array([1.  , 0.92, 0.96])

In [120]:
kernels=['rbf','linear']

In [121]:
c=[10,20,30,40,50,60]

In [122]:
a=[]

In [123]:
for i in kernels:
    for j in c:
        cvs=cross_val_score(svm.SVC(kernel=i,C=j,gamma='auto'),df.data,df.target,cv=4)
        x=np.average(cvs)
        a.append({i:x,j:x})
        

In [124]:
import numpy as np

In [125]:
len(a)

12

In [126]:
a

[{'rbf': 0.9735064011379801, 10: 0.9735064011379801},
 {'rbf': 0.9601706970128023, 20: 0.9601706970128023},
 {'rbf': 0.9601706970128023, 30: 0.9601706970128023},
 {'rbf': 0.9735064011379801, 40: 0.9735064011379801},
 {'rbf': 0.9667496443812233, 50: 0.9667496443812233},
 {'rbf': 0.9733285917496444, 60: 0.9733285917496444},
 {'linear': 0.9733285917496444, 10: 0.9733285917496444},
 {'linear': 0.9800853485064012, 20: 0.9800853485064012},
 {'linear': 0.9733285917496444, 30: 0.9733285917496444},
 {'linear': 0.9733285917496444, 40: 0.9733285917496444},
 {'linear': 0.966394025604552, 50: 0.966394025604552},
 {'linear': 0.966394025604552, 60: 0.966394025604552}]

In [127]:
#Now using Grid Search

In [131]:
from sklearn.model_selection import GridSearchCV

In [137]:
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[10,20,30,40,50,1],
    'kernel':['linear','rbf']
},cv=5)

In [138]:
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30, 40, 50, 1],
                         'kernel': ['linear', 'rbf']})

In [139]:
clf.cv_results_

{'mean_fit_time': array([0.00225468, 0.00307684, 0.00040555, 0.00020576, 0.00020747,
        0.00396481, 0.00079737, 0.        , 0.00312419, 0.00019927,
        0.00030169, 0.00152102]),
 'std_fit_time': array([0.00169849, 0.00321449, 0.0004968 , 0.00041151, 0.00041494,
        0.00666308, 0.00097657, 0.        , 0.00624838, 0.00039854,
        0.00060339, 0.00090475]),
 'mean_score_time': array([0.00214567, 0.00277939, 0.00043964, 0.00118947, 0.00160851,
        0.00064111, 0.        , 0.0031332 , 0.00017476, 0.        ,
        0.00019937, 0.00089417]),
 'std_score_time': array([0.0020235 , 0.00326712, 0.00087929, 0.00237894, 0.00321703,
        0.00082306, 0.        , 0.0062664 , 0.00034952, 0.        ,
        0.00039873, 0.000819  ]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30, 40, 40, 50, 50, 1, 1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=obje

In [140]:
r=pd.DataFrame(clf.cv_results_)

In [142]:
r[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       10       linear         0.966667
1       10          rbf         0.958333
2       20       linear         0.975000
3       20          rbf         0.958333
4       30       linear         0.975000
5       30          rbf         0.958333
6       40       linear         0.975000
7       40          rbf         0.958333
8       50       linear         0.983333
9       50          rbf         0.958333
10       1       linear         0.975000
11       1          rbf         0.975000

In [143]:
clf.best_params_

{'C': 50, 'kernel': 'linear'}

In [144]:
clf.best_score_

0.9833333333333334

In [145]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [148]:
from sklearn.model_selection import RandomizedSearchCV

In [149]:
clf=RandomizedSearchCV(svm.SVC(gamma='auto'),{  'C': [1,10,20],
        'kernel': ['rbf','linear']},cv=5,n_iter=5,return_train_score=False)

In [150]:
clf.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [151]:
clf.cv_results_

{'mean_fit_time': array([0.00220165, 0.0031105 , 0.00229149, 0.00160794, 0.00210552]),
 'std_fit_time': array([0.00163385, 0.00119891, 0.00373141, 0.00321589, 0.00302855]),
 'mean_score_time': array([0.00330272, 0.00209179, 0.00187998, 0.00152893, 0.0009923 ]),
 'std_score_time': array([0.00260011, 0.00137059, 0.00207641, 0.00305786, 0.00122021]),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'rbf', 'linear', 'linear'],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 20, 10, 1, 20],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 1},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.95833333, 0.95833333, 0.95833333, 0.95833333, 0.95833333]),
 'split1_test_score': array([1.        , 0.9583333

In [155]:
pd.DataFrame(clf.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.975000
1      20          rbf         0.958333
2      10          rbf         0.958333
3       1       linear         0.975000
4      20       linear         0.975000

In [156]:
clf.best_params_

{'kernel': 'rbf', 'C': 1}

In [157]:
clf.best_score_

0.975

In [158]:
from sklearn.svm import SVC

In [159]:
from sklearn.ensemble import RandomForestClassifier

In [160]:
from sklearn.linear_model import LogisticRegression

In [163]:
#nested_dict = {'dict1': {'key_A': 'value_A'},
   #            'dict2': {'key_B': 'value_B'}}

In [207]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}


In [208]:
scores=[]

In [180]:
x=model_params.items()

In [181]:
type(x)

dict_items

In [184]:
x

dict_items([('SVM', {'model': SVC(gamma='auto'), 'paramas': {'C': [1, 10, 20], 'Kernel': ['rbf', 'linear']}}), ('Random_Forest', {'model': RandomForestClassifier(), 'paramas': {'n_estimators': [1, 5, 10]}}), ('logistic_Regression', {'model': LogisticRegression(solver='liblinear'), 'paramas': {'C': [1, 5, 10]}})])

In [186]:
model_params.keys()

dict_keys(['SVM', 'Random_Forest', 'logistic_Regression'])

In [187]:
model_params.values()

dict_values([{'model': SVC(gamma='auto'), 'paramas': {'C': [1, 10, 20], 'Kernel': ['rbf', 'linear']}}, {'model': RandomForestClassifier(), 'paramas': {'n_estimators': [1, 5, 10]}}, {'model': LogisticRegression(solver='liblinear'), 'paramas': {'C': [1, 5, 10]}}])

In [214]:
for i ,j in model_params.items():
    clf=GridSearchCV(j['model'],j['params'],cv=5,return_train_score=False)
    clf.fit(x_train,y_train)
    s.append(
    {
        'model':i,
        'best_Score':clf.best_score_,
        'best_params':clf.best_params_
    })
    

In [212]:
s=[]

In [215]:
s

[{'model': 'svm',
  'best_Score': 0.9833333333333332,
  'best_params': {'C': 10, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_Score': 0.9833333333333334,
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_Score': 0.975,
  'best_params': {'C': 1}}]

In [216]:
pd.DataFrame(s)

model  best_Score                 best_params
0                  svm    0.983333  {'C': 10, 'kernel': 'rbf'}
1        random_forest    0.983333         {'n_estimators': 5}
2  logistic_regression    0.975000                    {'C': 1}

In [217]:
print("Jai Maa Kali")

Jai Maa Kali
