In [1]:
print("Jai Maa Kali")

Jai Maa Kali


In [2]:
import pandas as pd

In [3]:
from sklearn.datasets import load_digits

In [4]:
x=load_digits()

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
from sklearn.svm import SVC

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
import numpy as np

In [9]:
import matplotlib.pyplot as plt

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x.data,x.target,test_size=0.2)

In [15]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9527777777777777

In [16]:
svm=SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.3527777777777778

In [17]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9805555555555555

In [19]:
from sklearn.model_selection import KFold

In [22]:
kf=KFold(n_splits=3)

In [23]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [47]:
for train,test in kf.split([1,2,3,4,5,6,7,8,9]):
    print("train ,test: ",train,test)

train ,test:  [3 4 5 6 7 8] [0 1 2]
train ,test:  [0 1 2 6 7 8] [3 4 5]
train ,test:  [0 1 2 3 4 5] [6 7 8]


In [48]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [50]:
from sklearn.model_selection import StratifiedKFold

In [61]:
folds=StratifiedKFold(n_splits=3)

In [62]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [65]:
for train,test in folds.split(x.data,x.target):
    x_train,x_test,y_train,y_test=x.data[train],x.data[test],x.target[train],x.target[test]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

    

In [66]:
scores_logistic

[0.8948247078464107,
 0.9532554257095158,
 0.9098497495826378,
 0.8948247078464107,
 0.9532554257095158,
 0.9098497495826378]

In [83]:
#KfoldsCrossValidation
from sklearn.model_selection import StratifiedKFold
f=StratifiedKFold(n_splits=5)
scores_logistic = []
scores_svm = []
scores_rf = []
for train_index,test_index in f.split(x.data,x.target):
    #print("\ntrain : ,test : \n",train_index,test_index)
    x_train,x_test,y_train,y_test=x.data[train_index],x.data[test_index],x.target[train_index],x.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(gamma='auto'),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

In [84]:
scores_logistic

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.8941504178272981]

In [85]:
scores_svm

[0.4111111111111111,
 0.45,
 0.45403899721448465,
 0.44846796657381616,
 0.479108635097493]

In [86]:
scores_rf

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.9192200557103064]

In [87]:
from sklearn.model_selection import cross_val_score

In [90]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x.data, x.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [92]:
#Syntax:
#cross_val_score(model,x_features_data,target,cv=no of splits)

In [94]:
cross_val_score(SVC(gamma='auto'), x.data, x.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [95]:
cross_val_score(RandomForestClassifier(n_estimators=40),x.data, x.target,cv=3)

array([0.91652755, 0.94991653, 0.92821369])

In [96]:
#Parameter Tunning
cross_val_score(RandomForestClassifier(n_estimators=10),x.data, x.target,cv=3)

array([0.89649416, 0.91819699, 0.89482471])

In [97]:
cross_val_score(RandomForestClassifier(n_estimators=20),x.data, x.target,cv=3)

array([0.92821369, 0.93322204, 0.91318865])

In [98]:
cross_val_score(RandomForestClassifier(n_estimators=30),x.data, x.target,cv=3)

array([0.91986644, 0.95826377, 0.92320534])

In [99]:
cross_val_score(RandomForestClassifier(n_estimators=40),x.data, x.target,cv=3)

array([0.92821369, 0.94323873, 0.92654424])

In [100]:
cross_val_score(RandomForestClassifier(n_estimators=50),x.data, x.target,cv=3)

array([0.93489149, 0.94824708, 0.92821369])

In [101]:
print("Jai Maa Kali")

Jai Maa Kali
