In [1]:
print("Jai Maa Kali")

Jai Maa Kali


In [2]:
import pandas as pd


In [3]:
x=pd.read_csv('titanic.csv')

In [4]:
x.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [5]:
print("Jai Maa Kali")

Jai Maa Kali


In [6]:
print("Jai Maa Kali")

Jai Maa Kali


In [7]:
x.columns

Index(['PassengerId', 'Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [8]:
x.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1,inplace=True)

In [9]:
x.head(2)

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1

In [10]:
#Converting Categorical columns into Binary Values

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
c=OneHotEncoder(sparse_output=False)

In [13]:
c

OneHotEncoder(sparse_output=False)

In [14]:
cc=x.select_dtypes(include=['object']).columns.tolist()

In [15]:
cc

['Sex']

In [16]:
y=c.fit_transform(x[cc])

In [17]:
y

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [19]:
y=pd.DataFrame(y,columns=c.get_feature_names_out(cc))

In [20]:
y

Sex_female  Sex_male
0           0.0       1.0
1           1.0       0.0
2           1.0       0.0
3           1.0       0.0
4           0.0       1.0
..          ...       ...
886         0.0       1.0
887         1.0       0.0
888         1.0       0.0
889         0.0       1.0
890         0.0       1.0

[891 rows x 2 columns]

In [21]:
z=pd.concat([x,y],axis=1)

In [23]:
z.head()

Pclass     Sex   Age     Fare  Survived  Sex_female  Sex_male
0       3    male  22.0   7.2500         0         0.0       1.0
1       1  female  38.0  71.2833         1         1.0       0.0
2       3  female  26.0   7.9250         1         1.0       0.0
3       1  female  35.0  53.1000         1         1.0       0.0
4       3    male  35.0   8.0500         0         0.0       1.0

In [26]:
z.drop(['Sex'],axis=1)

Pclass   Age     Fare  Survived  Sex_female  Sex_male
0         3  22.0   7.2500         0         0.0       1.0
1         1  38.0  71.2833         1         1.0       0.0
2         3  26.0   7.9250         1         1.0       0.0
3         1  35.0  53.1000         1         1.0       0.0
4         3  35.0   8.0500         0         0.0       1.0
..      ...   ...      ...       ...         ...       ...
886       2  27.0  13.0000         0         0.0       1.0
887       1  19.0  30.0000         1         1.0       0.0
888       3   NaN  23.4500         0         1.0       0.0
889       1  26.0  30.0000         1         0.0       1.0
890       3  32.0   7.7500         0         0.0       1.0

[891 rows x 6 columns]

In [31]:
z.drop(['Sex_male','Sex'],axis=1,inplace=True)

In [32]:
z.head()

Pclass   Age     Fare  Survived  Sex_female
0       3  22.0   7.2500         0         0.0
1       1  38.0  71.2833         1         1.0
2       3  26.0   7.9250         1         1.0
3       1  35.0  53.1000         1         1.0
4       3  35.0   8.0500         0         0.0

In [36]:
z.isnull().sum()

Pclass        0
Age           0
Fare          0
Survived      0
Sex_female    0
dtype: int64

In [35]:
z.fillna(z.Age.mean(),inplace=True)

In [37]:
z.head()

Pclass   Age     Fare  Survived  Sex_female
0       3  22.0   7.2500         0         0.0
1       1  38.0  71.2833         1         1.0
2       3  26.0   7.9250         1         1.0
3       1  35.0  53.1000         1         1.0
4       3  35.0   8.0500         0         0.0

In [42]:
X=z.drop(['Survived'],axis=1)

In [43]:
Y=z['Survived']

In [45]:
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test=train_test_split(X,Y,test_size=0.2)

In [48]:
from sklearn.naive_bayes import GaussianNB

In [49]:
model=GaussianNB()

In [50]:
model

GaussianNB()

In [52]:
model.fit(X_train,y_train)

GaussianNB()

In [53]:
model.score(X_test,y_test)

0.7932960893854749

In [62]:
X_test[0:10]

Pclass        Age      Fare  Sex_female
30        1  40.000000   27.7208         0.0
878       3  29.699118    7.8958         0.0
787       3   8.000000   29.1250         0.0
194       1  44.000000   27.7208         1.0
259       2  50.000000   26.0000         1.0
40        3  40.000000    9.4750         1.0
717       2  27.000000   10.5000         1.0
883       2  28.000000   10.5000         0.0
306       1  29.699118  110.8833         1.0
664       3  20.000000    7.9250         0.0

In [64]:
y_test[0:10]

30     0
878    0
787    0
194    1
259    1
40     0
717    1
883    0
306    1
664    1
Name: Survived, dtype: int64

In [66]:
model.predict(X_test[0:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [67]:
model.predict_proba(X_test[0:10])

array([[0.74202648, 0.25797352],
       [0.96355344, 0.03644656],
       [0.94383967, 0.05616033],
       [0.06752234, 0.93247766],
       [0.22271427, 0.77728573],
       [0.4144625 , 0.5855375 ],
       [0.22100435, 0.77899565],
       [0.91930805, 0.08069195],
       [0.00227984, 0.99772016],
       [0.95887884, 0.04112116]])

In [69]:
from sklearn.model_selection import cross_val_score

In [70]:
cross_val_score(model,X_train,y_train,cv=5)

array([0.78321678, 0.77622378, 0.71830986, 0.81690141, 0.77464789])

In [71]:
#cross_val_score(model,data{input},data{output},cv=no.of splits)

In [72]:
x=pd.read_csv('spam.csv')

In [73]:
x.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [76]:
x.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [77]:
x['spam']=x['Category'].apply(lambda x: 0 if x=='ham' else 1)

In [78]:
x.head(4)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0

In [79]:
from sklearn.feature_extraction.text import CountVectorizer

In [80]:
v=CountVectorizer()

In [81]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x.Message,x.spam)

In [82]:
x_train

1388    Hope ur head doesn't hurt 2 much ! Am ploughin...
4587    Mila, age23, blonde, new in UK. I look sex wit...
4034    I am taking you for italian food. How about a ...
3386                                            Ok can...
1702    Can come my room but cannot come my house cos ...
                              ...                        
1802                             I wanna watch that movie
1217    You have 1 new voicemail. Please call 08719181...
2365    Ok then no need to tell me anything i am going...
172     Hmmm.. Thk sure got time to hop ard... Ya, can...
4503                            Wot is u up 2 then bitch?
Name: Message, Length: 4179, dtype: object

In [83]:
from sklearn.feature_extraction.text import CountVectorizer

In [84]:
v=CountVectorizer()

In [96]:
b=v.fit_transform(x_train)

In [97]:
b

<4179x7506 sparse matrix of type '<class 'numpy.int64'>'
	with 55843 stored elements in Compressed Sparse Row format>

In [100]:
b.toarray().shape

(4179, 7506)

In [103]:
from sklearn.naive_bayes import MultinomialNB

In [104]:
model=MultinomialNB()

In [105]:
model

MultinomialNB()

In [106]:
model.fit(b,y_train)

MultinomialNB()

In [107]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [111]:
c=v.transform(emails)

In [117]:
#Email spam filter Naive Bayes

In [172]:

df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [173]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [174]:
df['spam']=df.Category.apply(lambda x: 0 if x=='ham' else 1)

In [175]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [176]:
from sklearn.model_selection import train_test_split

In [130]:
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam)

In [177]:
from sklearn.feature_extraction.text import CountVectorizer

In [178]:
c=CountVectorizer()

In [179]:
b=c.fit_transform(df.Message.values)

In [140]:
from sklearn.naive_bayes import MultinomialNB

In [142]:
model=MultinomialNB()

In [143]:
model.fit(b,y_train)

MultinomialNB()

In [144]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [145]:
emails

['Hey mohan, can we get together to watch footbal game tomorrow?',
 'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']

In [155]:
n=v.transform(emails)

In [254]:
#model.score(x_test_count,y_test)

In [170]:
x_test_count=v.transform(x_test)

In [184]:
#Multinomial

In [232]:
x = pd.read_csv("spam.csv")
x.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [233]:
x['spam']=x.Category.apply(lambda x: 1 if x=='spam' else 0)

In [239]:
X=x['Message']
y=x['spam']

In [240]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [241]:
x.spam.shape

(5572,)

In [220]:
#Pipeline

In [242]:
from sklearn.pipeline import Pipeline

In [243]:
clf=Pipeline([('CV',CountVectorizer()), ('model', MultinomialNB())])

In [245]:
clf.fit(X_train,y_train)

Pipeline(steps=[('CV', CountVectorizer()), ('model', MultinomialNB())])

In [246]:
clf.score(X_test,y_test)

0.979372197309417

In [247]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Free entry in 2 a wkly comp to win',
    'daddddddddddddd'
]

In [248]:
clf.predict(emails)

array([0, 1, 1, 0], dtype=int64)

In [249]:
#Pipeline syntax

In [251]:
#clf=Pipeline([('Scaler',function()),('model',SVM())])

In [252]:
#clf.fit(x_train,y_train)

In [253]:
print("Jai Maa Kali")

Jai Maa Kali
