In [1]:
print("Jai Maa Kali")

Jai Maa Kali


In [2]:
#Pickle

In [4]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [11]:
X = pd.read_csv("predictions.csv")
X=X[['area','Price']]

In [12]:
X

area  Price
0   1000   1000
1   1500   1500
2   2300   2300
3   3540   3540
4   4120   4120
5   4560   4560
6   5490   5490
7   3460   3460
8   4750   4750
9   2300   2300
10  9000   9000
11  8600   8600
12  7100   7100

In [10]:
c=linear_model.LinearRegression()

In [21]:
x=X['area']
v=x.values.reshape(-1,1)

In [17]:
y=X["Price"]

In [22]:
c.fit(v,y)

LinearRegression()

In [25]:
c.predict([[8200]])

array([8200.])

In [27]:
c.coef_

array([1.])

In [28]:
c.intercept_

2.7284841053187847e-12

In [29]:
#Pickle

In [30]:
import pickle

In [33]:
with open('model_pickle','wb') as f:
    pickle.dump(c,f)
    #Saving model

In [36]:
with open('model_pickle','rb')  as f:
    z=pickle.load(f)
    #loading model

In [37]:
z.predict([[3000]])

array([3000.])

In [38]:
z.coef_

array([1.])

In [39]:
z.intercept_

2.7284841053187847e-12

In [45]:
#Joblib
#from sklearn.externals import joblib

In [43]:
import joblib

In [46]:
joblib.dump(c,'model_joblib')

['model_joblib']

In [47]:
z=joblib.load('model_joblib')

In [48]:
z.predict([[4000]])

array([4000.])

In [50]:
z.coef_

array([1.])

In [51]:
z.intercept_

2.7284841053187847e-12

In [52]:
print("Jai Maa Kali")

Jai Maa Kali
